### ISSUE TITLE
Try flexlayout?

### ISSUE THREAD

**Issue by Piasy** [gavinliu/Android-ScaleLayout#1]

**Comment by gavinliu** [comment]
这个和 flexlayout 不是同一个东西，flexlayout 是自动换行，这个是根据屏幕尺寸缩放。

**Comment by Piasy** [comment]
I mean this one https://github.com/mmin18/FlexLayout

**Comment by gavinliu** [comment]
所噶，看错了，看成了google的 flexbox-layout 。

---

确实现在类似的框架很多，但是思想不通和诉求不同，当时设计这个考虑到
1. 我们App只需要竖屏且都是手机，缩放是最简单，最有效的方式（这里经过了千万用户的验证，_魅族视频项目 2014 - 至今_）
2. 要接入简单，升级成本低，不能有太大的学习成本，毕竟是要团队合作的。

我这个代码实现上是借鉴 `android-percent-support`。

`FlexLayout` 我觉得有个问题
1. 学习成本 大：定义了很多操作符，各种位置的方式，说实话略显复杂。
2. 升级成本 大：没有重用android原生的属性，意味着xml基本要重新。

Github 上的 `ScaleLayout` 版本还太老了，目前我们内部迭代的，升级 完全不需要重新编写xml即可完成适配，过段时间整理下代码，再传上来。
