### ISSUE TITLE
这个和zhy 的那个百分比适配库原理是一样的么。。

### ISSUE THREAD

**Issue by Liloupar** [gavinliu/Android-ScaleLayout#2]

**Comment by gavinliu** [comment]
对，几乎是一模一样的。他哪个还维护得比较好，不过也存在一些问题，我这个传了一版就没更新了，因为公司在用这份代码，更新全在公司内部了。过段时间看看能不能整理一下发上来。

话说问一句，这个项目我都没发到社区推广，你们是如何发现这个项目的？

**Comment by Liloupar** [comment]
我关注了的人star了。。我就看见了

**Comment by Liloupar** [comment]
这种动态计算百分比会对性能上有一些影响么？

**Comment by gavinliu** [comment]
开销很小，我在魅族MX5测试，嵌套100个View，多消耗的时间只有 10+毫秒
