### ISSUE TITLE
这个库以后会稳定更新么

### ISSUE THREAD

**Issue by xq598359628** [gavinliu/Android-ScaleLayout#4]
这个库以后会稳定更新么？？ 感觉这个库很不错的

**Comment by xq598359628** [comment]
设计图的相关属性没有加啊？这个Readme更新下，给个最新的使用方法吧。另外，我想问下，是不是UI给的px，我直接写PX，加上app:layout_scale_by="width"，是自动会根据不同手机的密度去缩放么

**Comment by gavinliu** [comment]
嗯，readme 我这周末更新一波， 最新代码看 dev 分支。

**Comment by gavinliu** [comment]
已更新
