### ISSUE TITLE
Design mode error

### ISSUE THREAD

**Issue by carmas123** [gavinliu/Android-ScaleLayout#7]
When I use this lib in design mode I got always this exception:

java.lang.IllegalArgumentException: You must call ScaleConfig.create first

regards

**Comment by gavinliu** [comment]
First step, you need initialize the lib.

-------

You can extends ``Application`` 

eg: 

### MyApplication.java

```java 
public class MyApplication extends Application {

    @Override
    public void onCreate() {
        ScaleConfig.create(this,
            1080, // Design Width
            1920, // Design Height
            3,    // Design Density
            ScaleConfig.DIMENS_UNIT_DP); 
    }
}
```

### AndroidManifest.xml

```xml
 <application
        android:name=".MyApplication"
```

**Comment by carmas123** [comment]
Oh yes I do that, but this at Runtime not in Designtime

**Comment by gavinliu** [comment]
sorry, I understand your means now.

this is a bug, I will fix this.

**Comment by carmas123** [comment]
Thank you so much

**Comment by carmas123** [comment]
Please can you also update your readme illustrating gradle

```
dependencies {
    compile 'cn.gavinliu.android.lib:ScaleLayout:1.0.1'
}
```

**Comment by gavinliu** [comment]
please, try a new version.

```
compile 'cn.gavinliu.android.lib:ScaleLayout:1.0.2'
```

**Comment by carmas123** [comment]
All work fine thank you
